### ISSUE TITLE
could not find expected ':'

### ISSUE THREAD

**Issue by seekingdeep** [tson1997/SDL-Document-Image-Generation#1]
Hi there,
This repository is amazing!
and i understand that you are currently finalizing this repository, yet i am eager to test it

After removing `<<<<<<< HEAD` and `=======` and `>>>>>>> 60067811e5ad5b88814b1ae5fbf1df85b0ff3524`
from `flexible_layout.py`, i get some error when trying to run.

```
(udet) home@home-lnx:~/programs/SDL-Document-Image-Generation$ python flexible_layout.py --config_file configs/page.yaml
Traceback (most recent call last):
  File "flexible_layout.py", line 145, in <module>
    args.merge_from_file(config_file)
  File "/home/home/programs/SDL-Document-Image-Generation/helper/config.py", line 6, in merge_from_file
    res = yaml.load(open(path,'r'), Loader=yaml.Loader)
  File "/home/home/anaconda3/envs/udet/lib/python3.7/site-packages/yaml/__init__.py", line 114, in load
    return loader.get_single_data()
  File "/home/home/anaconda3/envs/udet/lib/python3.7/site-packages/yaml/constructor.py", line 49, in get_single_data
    node = self.get_single_node()
  File "/home/home/anaconda3/envs/udet/lib/python3.7/site-packages/yaml/composer.py", line 36, in get_single_node
    document = self.compose_document()
  File "/home/home/anaconda3/envs/udet/lib/python3.7/site-packages/yaml/composer.py", line 55, in compose_document
    node = self.compose_node(None, None)
  File "/home/home/anaconda3/envs/udet/lib/python3.7/site-packages/yaml/composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/home/home/anaconda3/envs/udet/lib/python3.7/site-packages/yaml/composer.py", line 127, in compose_mapping_node
    while not self.check_event(MappingEndEvent):
  File "/home/home/anaconda3/envs/udet/lib/python3.7/site-packages/yaml/parser.py", line 98, in check_event
    self.current_event = self.state()
  File "/home/home/anaconda3/envs/udet/lib/python3.7/site-packages/yaml/parser.py", line 428, in parse_block_mapping_key
    if self.check_token(KeyToken):
  File "/home/home/anaconda3/envs/udet/lib/python3.7/site-packages/yaml/scanner.py", line 115, in check_token
    while self.need_more_tokens():
  File "/home/home/anaconda3/envs/udet/lib/python3.7/site-packages/yaml/scanner.py", line 152, in need_more_tokens
    self.stale_possible_simple_keys()
  File "/home/home/anaconda3/envs/udet/lib/python3.7/site-packages/yaml/scanner.py", line 292, in stale_possible_simple_keys
    "could not find expected ':'", self.get_mark())
yaml.scanner.ScannerError: while scanning a simple key
  in "configs/page.yaml", line 2, column 1
could not find expected ':'
  in "configs/page.yaml", line 3, column 1
```

**Comment by sonnguyenasu** [comment]
Hello, thanks for your interest in the repository.
Can you clone and check it again? I have updated the page.YAML file. Apparently, there is a conflict in the YAML file and I have removed it. Thanks for mentioning your issue.

**Comment by seekingdeep** [comment]
Thanks,
also, inorder to test the repository directly, it might be good to include a small sample of:
`assets/corpus/test.txt`
`assets/all_plot`
`assets/formula`

**Comment by sonnguyenasu** [comment]
Hello, 
I have added the example as you recommended, please kindly check it. Thanks for your contribution :D
